Done project-2
AirstaNs/java-course-2023 pull request #12
Opened 2023-11-05 17:42 UTC by AirstaNs

2023-11-13 13:01 UTC, nexen505 requested changes

2023-11-13 13:01 UTC, nexen505 commented on src/main/java/edu/project2/solver/AStarSolver.java
> +        PriorityQueue<Point> openSet = new PriorityQueue<>(Comparator.comparingDouble(fScore::get));
Мысль: выглядит так, что тут можно использовать `TreeSet` с правильным компаратором, чтобы оптимизировать `contains`.

2023-11-13 15:16 UTC, AirstaNs commented on src/main/java/edu/project2/solver/AStarSolver.java
> +        PriorityQueue<Point> openSet = new PriorityQueue<>(Comparator.comparingDouble(fScore::get));
Добавил TreeSet

2023-11-16 13:47 UTC, nexen505 approved these changes

2023-11-16 14:22 UTC, merged