done HW-5
AirstaNs/java-course-2023 pull request #13
Opened 2023-11-13 18:48 UTC by AirstaNs

2023-11-15 11:50 UTC, nexen505 requested changes

2023-11-15 11:50 UTC, nexen505 commented on src/main/java/edu/hw5/Task2.java
> +                .datesUntil(nextYear)
Проблема: итерация происходит подневно, хотя нам достаточно смотреть 13 числа каждого месяца.

Предложение: уточнить начальную дату поиска и воспользоваться перегрузкой данного метода с шагом месяц.

2023-11-15 11:50 UTC, nexen505 commented on src/main/java/edu/hw5/Task5.java
> +    private static final Pattern PATTERN = Pattern.compile("[А-ЯеЁ]\\d{3}[А-ЯеЁ]{2}\\d{3}");
Проблема: регулярное выражение не соответствует спецификации российского номера https://ru.wikipedia.org/wiki/%D0%A0%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B5_%D0%B7%D0%BD%D0%B0%D0%BA%D0%B8_%D1%82%D1%80%D0%B0%D0%BD%D1%81%D0%BF%D0%BE%D1%80%D1%82%D0%BD%D1%8B%D1%85_%D1%81%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B2_%D0%B2_%D0%A0%D0%BE%D1%81%D1%81%D0%B8%D0%B8#%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D1%82

Предложение: уточнить регулярное выражение.

2023-11-15 11:50 UTC, nexen505 commented on src/main/java/edu/hw5/Task5.java
> +    public static boolean isValidateNumber(String password) {
Опечатка:

```java suggestion
    public static boolean isValidNumber(String autonumber) {
```

2023-11-15 11:50 UTC, nexen505 commented on src/test/java/edu/hw5/Task6Test.java
> +public class Task6Test {
Предложение: добавить тест на случай, если подстрока поиска представляет из себя регулярное выражение. В таком случае должна искаться именно она, а не подходящий под нее кусок исходной строки.

2023-11-15 12:58 UTC, AirstaNs commented on src/test/java/edu/hw5/Task6Test.java
> +public class Task6Test {
Недочеты были исправлены.

2023-11-16 12:50 UTC, nexen505 commented on src/test/java/edu/hw5/Task2Test.java
> +        assertEquals(LocalDate.of(2023, 5, 13), result);
Проблема: 13 мая 2023 - суббота :)

Предложение: исправить тест и реализацию метода.

2023-11-16 12:50 UTC, nexen505 commented on src/test/java/edu/hw5/Task6Test.java
> +public class Task6Test {
Насколько понимаю, в текущей реализации сделано ровно наоборот: ищется подходящий под регулярку кусок строки.

Для примера: в строке `as\dfdsa` должна найтись подстрока `\df`.

2023-11-16 12:53 UTC, nexen505 requested changes

2023-11-16 12:53 UTC, nexen505 commented on src/main/java/edu/hw5/Task5.java
> +    private static final Pattern PATTERN = Pattern.compile("[АВЕКМНОРСТУХ]\\d{3}[АВЕКМНОРСТУХ]{2}\\d{3}");
Проблемы: 
- в центре не может быть трех нулей,
- регион может быть из двух цифр, но не обоих нулей.

Предложение: уточнить регулярное выражение и добавить соответствующие тесты.

2023-11-16 16:14 UTC, AirstaNs commented on src/main/java/edu/hw5/Task5.java
> +    private static final Pattern PATTERN = Pattern.compile("[АВЕКМНОРСТУХ]\\d{3}[АВЕКМНОРСТУХ]{2}\\d{3}");
Проблемы были исправлены.

2023-11-17 08:44 UTC, nexen505 approved these changes

2023-11-17 11:17 UTC, merged