done hw-6
AirstaNs/java-course-2023 pull request #14
Opened 2023-11-18 20:40 UTC by AirstaNs

2023-11-20 14:20 UTC, nexen505 requested changes

2023-11-20 14:20 UTC, nexen505 commented on src/main/java/edu/hw6/task1/DiskMap.java
> +            LOGGER.error(e.getMessage());
Мысль: на мой взгляд, такие исключение "проглатывать" неправильно, так как они важны для понимания, что `DiskMap` не прочитается или не сохранится, - лучше их пробрасывать наружу.

2023-11-20 14:20 UTC, nexen505 commented on src/main/java/edu/hw6/task1/DiskMap.java
> +    public void read() {
Проблема: методы записи или чтения не встроены в логику реализации интерфейса `Map`.

Предложение: вызывать их внутри соответствующих операций.

2023-11-20 14:20 UTC, nexen505 commented on src/main/java/edu/hw6/task1/DiskMap.java
> +            List<String> strings = Files.readAllLines(path, charset);
Проблема: на больших файлах читать все строки в память неэффективно.

Предложение: читать файл строка за строкой.

2023-11-20 14:20 UTC, nexen505 commented on src/main/java/edu/hw6/task5/HackerNews.java
> +    private final HttpClient client;
Проблема: ресурс не закрывается.

Предложение: сделать `HackerNews implements AutoCloseable` и закрывать клиент.

2023-11-20 14:20 UTC, nexen505 commented on src/main/java/edu/hw6/task6/PortScanner.java
> +            socket.connect(new InetSocketAddress("localhost", port), timeout);
Косметика: вместо подобного можно использовать `ServerSocket`.

2023-11-20 14:20 UTC, nexen505 commented on src/test/java/edu/hw6/task1/DiskMapTest.java
> +    void testDiskMap() {
Предложение: для удобства восприятия разбить на тесты отдельных операций.

2023-11-20 14:20 UTC, nexen505 commented on src/test/java/edu/hw6/task6/PortInfoTest.java
> +    void portInfo_ShouldCorrectlyHoldData() {
Предложение: добавить тесты на занятые порты.

2023-11-21 11:53 UTC, AirstaNs commented on src/main/java/edu/hw6/task1/DiskMap.java
> +    public void read() {
Возможно чтение стоит использовать при инициализации в конструкторе, но метод save() вызывать при каждом изменении коллекции - тяжело по ресурсам, а внутренняя мапа, представляет собой как раз решение этой проблемы, поэтому состояние записи я предпочел контролировать с внешней стороны.

2023-11-23 13:15 UTC, nexen505 commented on src/main/java/edu/hw6/task1/DiskMap.java
> +    public void read() {
Пусть будет так.

2023-11-23 13:16 UTC, nexen505 approved these changes

2023-11-23 15:21 UTC, merged