done HW-7
AirstaNs/java-course-2023 pull request #16
Opened 2023-11-26 15:16 UTC by AirstaNs

2023-11-27 12:46 UTC, nexen505 requested changes

2023-11-27 12:46 UTC, nexen505 commented on src/main/java/edu/hw7/task1/MultiCoreProcessor.java
> +        executor.shutdown();
Косметика: в целом, подобного эффекта тут и в других заданиях и тестах можно добиться использованием `ExecutorService#close`.

2023-11-27 12:46 UTC, nexen505 commented on src/main/java/edu/hw7/task3/SynchronizedDatabase.java
> +            database.put(person.id(), person);
Предложение: учесть коллизию, если вдруг по тому же идентификатору добавляют другого `Person`.

2023-11-27 12:46 UTC, nexen505 commented on src/main/java/edu/hw7/task3/PersonDatabase.java
> +public interface PersonDatabase {
Проблема: кажется, не хватает требуемой по заданию реализации с использованием `synchronized`.

Предложение: добавить еще одну реализацию в соответствии с заданием.

2023-11-27 12:46 UTC, nexen505 commented on src/test/java/edu/hw7/task4/PiMonteCarloTest.java
> +class PiMonteCarloTest {
Предложение:
1) добавить параметризованный тест для локальной проверки отчета производительности, требуемого в задании,
2) удостовериться, что тестирование на одном потоке не создает пул из одного потока за ненадобностью (можно добавить отдельную реализацию метода для однопоточного расчета).

2023-11-29 15:31 UTC, AirstaNs commented on src/test/java/edu/hw7/task4/PiMonteCarloTest.java
> +class PiMonteCarloTest {
Замечания были исправлены

2023-11-30 13:14 UTC, nexen505 requested changes

2023-11-30 13:14 UTC, nexen505 commented on src/main/java/edu/hw7/task1/MultiCoreProcessor.java
> +        executor.close();
Проблема: пул не закроется в случае ошибок ранее.

Предложение: воспользоваться `try-with-resources`.

2023-11-30 13:14 UTC, nexen505 commented on src/main/java/edu/hw7/task4/PiMonteCarlo.java
> +        executor.close();
Проблема: пул не закроется в случае ошибок ранее.

Предложение: воспользоваться `try-with-resources`.

2023-11-30 13:14 UTC, nexen505 commented on src/main/java/edu/hw7/task4/PiMonteCarlo.java
> +            final int iterationsPerThread = totalIterations / threadCount;
Проблема: при целочисленном делении есть риск потерять остаток от деления.

Предложение: добавить расчет оставшихся точек в пул.

2023-11-30 13:14 UTC, nexen505 commented on src/test/java/edu/hw7/task4/PiMonteCarloTest.java
> +        double seconds = duration.getSeconds() + duration.getNano() / 1e9;
Косметика: можно упростить

```java suggestion
        double seconds = duration.toSeconds();
```

2023-11-30 13:14 UTC, nexen505 commented on src/test/java/edu/hw7/task4/PiMonteCarloTest.java
> +        Instant startTime = Instant.now();
Проблема: так есть риск потери точности длительности.

Предложение: для корректной точности при вычислении времени выполнения лучше пользоваться замерами через `System#nanoTime`.

2023-11-30 15:00 UTC, AirstaNs commented on src/test/java/edu/hw7/task4/PiMonteCarloTest.java
> +        Instant startTime = Instant.now();
Замечания были учтены

2023-12-01 11:32 UTC, nexen505 approved these changes

2023-12-02 19:00 UTC, merged