done hw-8
AirstaNs/java-course-2023 pull request #17
Opened 2023-12-03 20:57 UTC by AirstaNs

2023-12-05 13:32 UTC, nexen505 requested changes

2023-12-05 13:32 UTC, nexen505 commented on src/main/java/edu/hw8/task1/EchoClient.java
> +                Thread.sleep(wait);
Мысль: думаю, можно уйти от `Thread.sleep` в сторону чтения из `BufferedReader`.

2023-12-05 13:32 UTC, nexen505 commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +        if (isRunning) {
Косметика: в обратном случае можно выбрасывать `RejectedExecutionException`, например.

2023-12-05 13:32 UTC, nexen505 commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +            isFinished = taskQueue.isEmpty();
Проблема: цикл busy-waiting получается.

Предложение: ждать опустошения очереди с каким-то таймаутом и принудительно ее чистить, если после завершения потоков там остались задачи.

2023-12-05 13:32 UTC, nexen505 commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +                    Thread.currentThread().interrupt();
Мысль: думаю, в этой ситуации надо исключение пробросить наверх и прервать цикл.

2023-12-06 02:46 UTC, AirstaNs commented on src/main/java/edu/hw8/task2/FixedThreadPool.java
> +                    Thread.currentThread().interrupt();
Замечания были учтены.

2023-12-06 08:17 UTC, nexen505 approved these changes

2023-12-08 11:02 UTC, merged