Done HW-2
AirstaNs/java-course-2023 pull request #2
Opened 2023-10-22 12:01 UTC by AirstaNs

2023-10-26 07:14 UTC, nexen505 requested changes

2023-10-26 07:14 UTC, nexen505 commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +        Throwable cause = new Throwable();
Косметика: тут можно сузить тип до `Exception`.

2023-10-26 07:14 UTC, nexen505 commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +        throw new ConnectionException(msg, cause.getCause());
Проблема: оригинальная причина теряется за счет дополнительного вызова `getCause`.

Предложение: передавать `cause`, как есть.

2023-10-26 11:02 UTC, AirstaNs commented on src/main/java/edu/hw2/task3/PopularCommandExecutor.java
> +        throw new ConnectionException(msg, cause.getCause());
ДЗ было доработано

2023-10-27 08:48 UTC, nexen505 approved these changes

2023-10-27 12:12 UTC, merged