Done project-1
AirstaNs/java-course-2023 pull request #4
Opened 2023-10-22 20:05 UTC by AirstaNs

2023-10-26 07:07 UTC, nexen505 requested changes

2023-10-26 07:07 UTC, nexen505 commented on src/main/java/edu/project1/game/ConsoleHangman.java
> +        Scanner scanner = new Scanner(System.in);
Проблема: ресурс не закрывается.

Предложение: вынести его наружу с закрытием и использовать как параметр метода или поле.

2023-10-26 07:07 UTC, nexen505 commented on src/main/java/edu/project1/game/GameMessagesPrinter.java
> +        logger.info(REQUEST_INPUT);
Проблема: пользователь на старте игры не знает размер слова, который ему надо угадать.

Предложение: добавить пользовательскую подсказку.

2023-10-26 07:07 UTC, nexen505 commented on src/main/java/edu/project1/game/ConsoleHangman.java
> +            player.makeMistake();
Проблема: повторный ввод ранее не угаданной буквы приведет к поражению.

Предложение: учесть этот сценарий и не тратить попытку пользователя при его ошибке.

2023-10-26 07:07 UTC, nexen505 commented on src/main/java/edu/project1/game/GameMessagesPrinter.java
> +    public static final String INVALID_INPUT = "Invalid input. Try again.";
Проблема: пользователь не знает, что в его вводе не так.

Предложение: уточнить пользовательскую подсказку с просьбой ввести допустимый символ.

2023-10-26 07:07 UTC, nexen505 commented on src/main/java/edu/project1/model/Word.java
> +            if (actualWord[i] == lowerLetter && representation[i] == hiddenSymbol) {
Проблема: повторный ввод ранее угаданной буквы приведет к поражению.

Предложение: учесть этот сценарий и не тратить попытку пользователя при его ошибке.

2023-10-26 11:05 UTC, AirstaNs commented on src/main/java/edu/project1/model/Word.java
> +            if (actualWord[i] == lowerLetter && representation[i] == hiddenSymbol) {
Замечания были исправлены

2023-10-27 13:11 UTC, nexen505 approved these changes

2023-10-27 13:18 UTC, merged