Done HW-3
AirstaNs/java-course-2023 pull request #6
Opened 2023-10-25 13:19 UTC by AirstaNs

2023-10-31 12:09 UTC, nexen505 requested changes

2023-10-31 12:09 UTC, nexen505 commented on src/main/java/edu/hw3/Task3.java
> +            freqMap.put(s, count + 1);
Проблема: конструкция чтение+запись неатомарна и сложна для восприятия.

Предложение: использовать метод `java.util.Map#merge`

2023-10-31 12:09 UTC, nexen505 commented on src/main/java/edu/hw3/Task4.java
> +    public static String convertToRoman(int number) {
Проблема: у римских чисел есть стандартный диапазон, который тут не учтен.

Предложение: учесть его в реализации.

2023-11-01 14:55 UTC, AirstaNs commented on src/main/java/edu/hw3/Task4.java
> +    public static String convertToRoman(int number) {
Недостатки были исправлены

2023-11-02 14:13 UTC, nexen505 approved these changes

2023-11-02 15:35 UTC, merged